### ISSUE TITLE
Superfluous space character

### ISSUE THREAD

**Issue by michelkusters** [remkus/genesis-translations#7]
Hi Remkus,

I suggest removing the superfluous space character from the following string in the nl_NL translation: msgstr "Home ". Currently the space character is part of a hyperlink and thus underlined in some themes, which looks wrong.

Cheers!

**Comment by defries** [comment]
Sorry for the late reply, but this is something that should be changed in the [Dutch translation of the Genesis Framework](https://translate.studiopress.com/global/projects/genesis/genesis-2.5/nl/default/), not this plugin itself. I'll change this myself, but feel free to beat me to the punch @michelkusters :)
